### ISSUE TITLE
Running Example.toml shows: no sessions

### ISSUE THREAD

**Issue by oren** [ethagnawl/rmuxinator#1]
How to run the example?

```
start Example.toml
no sessions
```

**Comment by ethagnawl** [comment]
Hi, @oren!

Which version of tmux are you using?

**Comment by oren** [comment]
2.1 (ubuntu 16.04)

**Comment by ethagnawl** [comment]
That's a very old version of tmux (~5 years). I'd recommend upgrading if you can, since many new, nice features have been added in the meantime.

However, since I haven't established a support matrix for tmux yet, I'll try rolling back to see if I can reproduce and fix the issue.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ethagnawl** [comment]
I just rolled back to 2.1 and was not able to reproduce this issue (despite having an invalid .tmux.conf, killing the server, starting the server, etc.). So, I'm not sure where that leaves us.

For the time being, I'm going to put a stake in the ground and say that rmuxinator is going to focus on supporting >= tmux 2.8, which is what's currently available via Aptitude in Debian Buster (10). 

I'll revisit supporting older versions once I've got a CI pipeline setup that'll allow me to more easily test across a number of versions without having to muck with my system.
